var mysql = require('mysql2');

var con = mysql.createConnection({
  host: "localhost",
  user: "root",
  password: "Wad270188!",
  database: "mydb1"
});

con.connect(function(err) {
  if (err) throw err;
  console.log("Connected!");
  var sql = "INSERT INTO table3 (name, decription) VALUES ?";
  var values = [
    ['John', 'Moskov'],
    ['Peter', 'Petersburg'],
    ['Amy', 'Petersburg'],
    ['Hannah', 'Ryazan'],
    ['Michael', 'Moskov'],
    ['Sandy', 'Ryazan'],
    ['Betty', 'Petersburg'],
    ['Richard', 'Volgograd'],
    ['Susan', 'Moskov'],
    ['Vicky', 'Moskov'],
    ['Ben', 'Volgograd'],
    ['William', 'Volgograd'],
    ['Chuck', 'Volgograd'],
    ['Ivan', 'Moskov'],
    ['Vladimir', 'Rostov'],
    ['Aleksamdr', 'Moskov'],
    ['Eva', 'Sochi'],
    ['Elena', 'Petersburg'],
    ['Sergey', 'Moskov'],
    ['Petya', 'Sochi'],
    ['Anna', 'Rostov']
    ['John', 'Moskov'],
    ['Peter', 'Petersburg'],
    ['Amy', 'Petersburg'],
    ['Hannah', 'Ryazan'],
    ['Michael', 'Moskov'],
    ['Sandy', 'Ryazan'],
    ['Betty', 'Petersburg'],
    ['Richard', 'Volgograd'],
    ['Susan', 'Moskov'],
    ['Vicky', 'Moskov'],
    ['Ben', 'Volgograd'],
    ['William', 'Volgograd'],
    ['Chuck', 'Volgograd'],
    ['Ivan', 'Moskov'],
    ['Vladimir', 'Rostov'],
    ['Aleksamdr', 'Moskov'],
    ['Eva', 'Sochi'],
    ['Elena', 'Petersburg'],
    ['Sergey', 'Moskov'],
    ['Petya', 'Sochi'],
    ['Anna', 'Rostov'],
    ['John', 'Moskov'],
    ['Peter', 'Petersburg'],
    ['Amy', 'Petersburg'],
    ['Hannah', 'Ryazan'],
    ['Michael', 'Moskov'],
    ['Sandy', 'Ryazan'],
    ['Betty', 'Petersburg'],
    ['Richard', 'Volgograd'],
    ['Susan', 'Moskov'],
    ['Vicky', 'Moskov'],
    ['Ben', 'Volgograd'],
    ['William', 'Volgograd'],
    ['Chuck', 'Volgograd'],
    ['Ivan', 'Moskov'],
    ['Vladimir', 'Rostov'],
    ['Aleksamdr', 'Moskov'],
    ['Eva', 'Sochi'],
    ['Elena', 'Petersburg'],
    ['Sergey', 'Moskov'],
    ['Petya', 'Sochi'],
    ['Anna', 'Rostov'],
    ['John', 'Moskov'],
    ['Peter', 'Petersburg'],
    ['Amy', 'Petersburg'],
    ['Hannah', 'Ryazan'],
    ['Michael', 'Moskov'],
    ['Sandy', 'Ryazan'],
    ['Betty', 'Petersburg'],
    ['Richard', 'Volgograd'],
    ['Susan', 'Moskov'],
    ['Vicky', 'Moskov'],
    ['Ben', 'Volgograd'],
    ['William', 'Volgograd'],
    ['Chuck', 'Volgograd'],
    ['Ivan', 'Moskov'],
    ['Vladimir', 'Rostov'],
    ['Aleksamdr', 'Moskov'],
    ['Eva', 'Sochi'],
    ['Elena', 'Petersburg'],
    ['Sergey', 'Moskov'],
    ['Petya', 'Sochi'],
    ['Anna', 'Rostov']
  ];
  con.query(sql, [values], function (err, result) {
    if (err) throw err;
    console.log("Number of records inserted: " + result.affectedRows);
  });
});